# Generated by Django 4.2.23 on 2025-08-01 15:21

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=512)),
                ('baseDir', models.CharField(max_length=512)),
                ('deviceDir', models.CharField(max_length=512)),
                ('fileType', models.CharField(max_length=256)),
                ('creationTime', models.DateTimeField(verbose_name='creation time')),
                ('size', models.BigIntegerField()),
                ('fileNum', models.IntegerField(null=True)),
                ('done', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdb.bank')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heartbeat', models.DateTimeField(null=True, verbose_name='should be updated with latest time')),
                ('currentScanNum', models.IntegerField(null=True)),
                ('currentProjectId', models.CharField(max_length=256, null=True)),
                ('currentState', models.CharField(max_length=256, null=True)),
                ('currentCycSpec', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanNum', models.IntegerField()),
                ('projectId', models.CharField(max_length=256)),
                ('startTime', models.DateTimeField(verbose_name='start time')),
                ('endTime', models.DateTimeField(null=True, verbose_name='duration time')),
                ('duration', models.IntegerField()),
                ('backend', models.CharField(max_length=256)),
                ('receiver', models.CharField(max_length=256)),
                ('mode', models.CharField(max_length=256)),
                ('source', models.CharField(max_length=256, null=True)),
                ('cycspec', models.BooleanField(default=False)),
                ('banks', models.ManyToManyField(to='mdb.bank')),
            ],
        ),
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plotFile', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/users/pmargani/tmp/qualityChecks'), upload_to='')),
                ('fileSize', models.BigIntegerField()),
                ('checkTime', models.DateTimeField(verbose_name='check time')),
                ('dataBlock', models.IntegerField()),
                ('packetIndex', models.BigIntegerField()),
                ('headerStr', models.TextField()),
                ('done', models.BooleanField(default=False)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdb.file')),
            ],
        ),
        migrations.CreateModel(
            name='Processing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processingType', models.CharField(max_length=256)),
                ('processedState', models.CharField(max_length=256)),
                ('processStartTime', models.DateTimeField(null=True, verbose_name='process start time')),
                ('processEndTime', models.DateTimeField(null=True, verbose_name='process end time')),
                ('details', models.TextField(null=True)),
                ('pid', models.IntegerField(null=True)),
                ('reprocess', models.BooleanField(default=False)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdb.bank')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdb.scan')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdb.scan'),
        ),
        migrations.CreateModel(
            name='BankStatusX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processingHeartbeat', models.DateTimeField(null=True, verbose_name='heartbeat of processing daemon')),
                ('qualityCheckHeartbeat', models.DateTimeField(null=True, verbose_name='heartbeat of quality check daemon')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdb.bank')),
                ('processing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mdb.processing')),
                ('qualityCheck', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mdb.qualitycheck')),
            ],
        ),
        migrations.CreateModel(
            name='BankStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processingHeartbeat', models.DateTimeField(null=True, verbose_name='heartbeat of processing daemon')),
                ('qualityCheckHeartbeat', models.DateTimeField(null=True, verbose_name='heartbeat of quality check daemon')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdb.bank')),
                ('processing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mdb.processing')),
                ('qualityCheck', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mdb.qualitycheck')),
            ],
        ),
    ]
